### ISSUE TITLE
Refactor - JSONSchema Just-In-Time Load

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/docs#58]
## Description

The JSONSchema files that become the reference data pages are currently slow to load due to their size, despite being stored locally. The contents should be pre-loaded immediately prior to being requested (React has a few clever ways of doing this) so that it is instantly available upon selecting the desired reference type.

# Tasks
- [ ] Investigate methods for pre-loading and parsing the JSONSchema content and select one. Document decision in comments.
- [ ] Implementation of chosen method.

## Issue Checklist
- [ ] Added Issue to the `hamlet roadmap` project.
- [ ] Assigned the appropriate Issue labels.
